name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build-3-10:
    uses: zuczekgnojak/cowptain/.github/workflows/build.yaml@main
    with:
      python-version: "3.10"

  test-3-10:
    needs: build-3-10
    uses: zuczekgnojak/cowptain/.github/workflows/test.yaml@main
    with:
      python-version: "3.10"

  lint:
    needs: build-3-10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linter: ["black", "flake8", "isort", "pylint"]
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: cowptain-3.10
          path: /tmp
      - name: load image
        run: docker load --input /tmp/cowptain-3.10.tar
      - name: lint
        run: docker run --rm cowptain:3.10 make ${{ matrix.linter }}

  build-3-11:
    uses: zuczekgnojak/cowptain/.github/workflows/build.yaml@main
    with:
      python-version: "3.11"

  test-3-11:
    needs: build-3-11
    uses: zuczekgnojak/cowptain/.github/workflows/test.yaml@main
    with:
      python-version: "3.11"

  build-3-12:
    uses: zuczekgnojak/cowptain/.github/workflows/build.yaml@main
    with:
      python-version: "3.12"

  test-3-12:
    needs: build-3-12
    uses: zuczekgnojak/cowptain/.github/workflows/test.yaml@main
    with:
      python-version: "3.12"
