name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: build ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["3.10", "3.11"]
    uses: jamilek/cowptain/.github/build.yaml
    with:
      python-version: ${{ matrix.version }}

  lint:
    name: ${{ matrix.linter }}
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        linter: ["black", "flake8", "isort", "pylint"]
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: cowptain-3.10
          path: /tmp
      - name: load image
        run: docker load --input /tmp/cowptain-3.10.tar
      - name: lint
        run: docker run --rm cowptain:3.10 make ${{ matrix.linter }}

  test:
    name: ${{ matrix.test }} - ${{ matrix.version }}
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        test: ["unit", "wsgiref", "gunicorn", "uwsgi"]
        version: ["3.10", "3.11"]
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: cowptain-${{ matrix.version }}
          path: /tmp
      - name: load image
        run: docker load --input /tmp/cowptain-${{ matrix.version }}.tar
      - name: test
        run: docker run --rm cowptain:${{ matrix.version }} make ${{ matrix.test }}
