name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: build ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["3.10", "3.11"]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: make build python_version=${{ matrix.version }}
      - name: save as file
        run: docker save cowptain:${{ matrix.version }} > cowptain-${{ matrix.version }}.tar
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cowptain-${{ matrix.version }}
          path: cowptain-${{ matrix.version }}.tar

  lint:
    name: ${{ matrix.linter }}
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        linter: ["black", "flake8", "isort", "pylint"]
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: cowptain-3.10
          path: cowptain-3.10.tar
      - name: load image
        run: docker load --input cowptain-3.10.tar
      - name: lint
        run: docker run --rm cowptain:3.10 make ${{ matrix.linter }}
