name: release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 -m pip install --upgrade build
      - run: python3 -m build
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
