name: release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 -m pip install --upgrade build
      - run: python3 -m build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - run: python3 -m pip install --upgrade twine
      - run: python3 -m twine upload dist/*

  update-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - run: ls dist
